app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


_security_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Auth:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout