security:
    encoders:
        AppBundle\Entity\User:
           algorithm: sha512
           encode-as-base64: true
           iterations: 10

    role_hierarchy:
        ROLE_ADMIN:    [ROLE_OPERATOR]
        ROLE_OPERATOR: [ROLE_AGENT]

    providers:
        main:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
                provider: main
            logout: true
            security: true
            anonymous: true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }