security:
    encoders:
        AppBundle\Entity\User:
           algorithm: sha512
           encode-as-base64: true
           iterations: 10

    role_hierarchy:
        ROLE_ADMIN:    [ROLE_OPERATOR]
        ROLE_OPERATOR: [ROLE_AGENT]
        ROLE_AGENT:    [ROLE_CLIENT]

    providers:
        main:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        main:
            provider: ~
            pattern:  ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /panel
            logout:
                path:   /logout
                target: /login


    access_control:
#        - { path: /operator/.*, role: ROLE_OPERATOR }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }